# printWidth: 80 # 80
tabWidth: 4 # 2
useTabs: true # false
semi: true # true
singleQuote: false # false
# trailingComma: none # none | es5 | all
bracketSpacing: false # true
# jsxBracketSameLine: false # false
# arrowParens: avoid # avoid | always
